/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void GUIdraw(PApplet appc, GWinData data) { //_CODE_:GUI:323055:
  appc.background(230);
} //_CODE_:GUI:323055:

public void primeDataButtonClicked(GButton source, GEvent event) { //_CODE_:primeDataButton:855167:
  savePrimeData();
} //_CODE_:primeDataButton:855167:

public void displayInfoBoxClicked(GCheckbox source, GEvent event) { //_CODE_:displayInfoBox:490563:
  infoWindow.setVisible(displayInfoBox.isSelected());
} //_CODE_:displayInfoBox:490563:

public void numCountFieldChange(GTextField source, GEvent event) { //_CODE_:numCountField:409762:
  numCount = int(numCountField.getText());
  if (numCount <= 358801) {
    numCountSettings();
    highlightSettings();
  }
} //_CODE_:numCountField:409762:

public void spiralShapeListChange(GDropList source, GEvent event) { //_CODE_:spiralShapeList:768705:
  spiralShape = spiralShapeList.getSelectedText();
  if (numCount <= 358801) {
    numCountSettings();
  }
} //_CODE_:spiralShapeList:768705:

public void showLabelsBoxClicked(GCheckbox source, GEvent event) { //_CODE_:showLabelsBox:532200:
  if (showLabelsBox.isSelected() && numCount <= 2025)
    showLabels = true;
  
  else 
    showLabels = false;
  
  if (numCount > 2025)
    showLabelsBox.setSelected(false);
} //_CODE_:showLabelsBox:532200:

public void polynomialBFieldChange(GTextField source, GEvent event) { //_CODE_:polynomialBField:341190:
  polynomial[1] = int(polynomialBField.getText());
  highlightSettings();
} //_CODE_:polynomialBField:341190:

public void hlPrimesBoxClicked(GCheckbox source, GEvent event) { //_CODE_:hlPrimesBox:461723:
  hlPrimes = hlPrimesBox.isSelected();
  highlightSettings();
} //_CODE_:hlPrimesBox:461723:

public void hlNonPrimesBoxClicked(GCheckbox source, GEvent event) { //_CODE_:hlNonPrimesBox:634263:
  hlNonPrimes = hlNonPrimesBox.isSelected();
  highlightSettings();
} //_CODE_:hlNonPrimesBox:634263:

public void polynomialCFieldChange(GTextField source, GEvent event) { //_CODE_:polynomialCField:542961:
  polynomial[2] = int(polynomialCField.getText());
  highlightSettings();
} //_CODE_:polynomialCField:542961:

public void demo1ButtonClicked(GButton source, GEvent event) { //_CODE_:demo1Button:328118:
  setDemoSettings(0, "529", "6", "1");
  getSettings();
} //_CODE_:demo1Button:328118:

public void demo2ButtonClicked(GButton source, GEvent event) { //_CODE_:demo2Button:360949:
  setDemoSettings(1, "256", "8", "3");
  getSettings();
} //_CODE_:demo2Button:360949:

public void demo3ButtonClicked(GButton source, GEvent event) { //_CODE_:demo3Button:645801:
  setDemoSettings(2, "919", "-8", "-13");
  getSettings();
} //_CODE_:demo3Button:645801:

public void screenshotButtonClicked(GButton source, GEvent event) { //_CODE_:screenshotButton:854915:
  takeScreenshot = true;
} //_CODE_:screenshotButton:854915:

synchronized public void infoWindowDraw(PApplet appc, GWinData data) { //_CODE_:infoWindow:919312:
  appc.background(230);
} //_CODE_:infoWindow:919312:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  GUI = GWindow.getWindow(this, "Settings", 0, 0, 290, 410, JAVA2D);
  GUI.noLoop();
  GUI.setActionOnClose(G4P.KEEP_OPEN);
  GUI.addDrawHandler(this, "GUIdraw");
  generalTitle = new GLabel(GUI, 100, 10, 80, 20);
  generalTitle.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  generalTitle.setText("GENERAL");
  generalTitle.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  generalTitle.setOpaque(false);
  primeDataButton = new GButton(GUI, 20, 35, 105, 30);
  primeDataButton.setText("Save prime data");
  primeDataButton.addEventHandler(this, "primeDataButtonClicked");
  displayInfoBox = new GCheckbox(GUI, 20, 69, 238, 30);
  displayInfoBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  displayInfoBox.setText("display program information window");
  displayInfoBox.setOpaque(false);
  displayInfoBox.addEventHandler(this, "displayInfoBoxClicked");
  spiralTitle = new GLabel(GUI, 100, 110, 80, 20);
  spiralTitle.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  spiralTitle.setText("SPIRAL");
  spiralTitle.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  spiralTitle.setOpaque(false);
  numCountField = new GTextField(GUI, 35, 140, 67, 20, G4P.SCROLLBARS_NONE);
  numCountField.setText("169");
  numCountField.setPromptText("type here...");
  numCountField.setOpaque(true);
  numCountField.addEventHandler(this, "numCountFieldChange");
  spiralShapeList = new GDropList(GUI, 160, 140, 90, 80, 3, 10);
  spiralShapeList.setItems(loadStrings("list_768705"), 0);
  spiralShapeList.addEventHandler(this, "spiralShapeListChange");
  numCountLabel = new GLabel(GUI, 11, 165, 122, 20);
  numCountLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  numCountLabel.setText("# of boxes in spiral");
  numCountLabel.setOpaque(false);
  spiralShapeLabel = new GLabel(GUI, 163, 165, 80, 20);
  spiralShapeLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  spiralShapeLabel.setText("spiral shape");
  spiralShapeLabel.setOpaque(false);
  showLabelsBox = new GCheckbox(GUI, 11, 200, 135, 20);
  showLabelsBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showLabelsBox.setText("show number labels");
  showLabelsBox.setOpaque(false);
  showLabelsBox.addEventHandler(this, "showLabelsBoxClicked");
  showLabelsBox.setSelected(true);
  showLabelsLabel = new GLabel(GUI, 11, 220, 240, 20);
  showLabelsLabel.setText("only shows for <= 2025 numbers in spiral");
  showLabelsLabel.setOpaque(false);
  polynomialTitle = new GLabel(GUI, 99, 250, 91, 20);
  polynomialTitle.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  polynomialTitle.setText("POLYNOMIAL");
  polynomialTitle.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  polynomialTitle.setOpaque(false);
  polynomialBField = new GTextField(GUI, 49, 280, 25, 17, G4P.SCROLLBARS_NONE);
  polynomialBField.setText("0");
  polynomialBField.setOpaque(true);
  polynomialBField.addEventHandler(this, "polynomialBFieldChange");
  polynomialALabel = new GLabel(GUI, 7, 280, 48, 20);
  polynomialALabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  polynomialALabel.setText("4x^2 + ");
  polynomialALabel.setOpaque(false);
  polynomialBLabel = new GLabel(GUI, 42, 280, 80, 20);
  polynomialBLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  polynomialBLabel.setText("x + ");
  polynomialBLabel.setOpaque(false);
  polynomialLabel = new GLabel(GUI, -5, 295, 154, 40);
  polynomialLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  polynomialLabel.setText("polynomial to highlight (input any integers)");
  polynomialLabel.setOpaque(false);
  hlPrimesBox = new GCheckbox(GUI, 10, 345, 137, 20);
  hlPrimesBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  hlPrimesBox.setText("highlight primes (red)");
  hlPrimesBox.setOpaque(false);
  hlPrimesBox.addEventHandler(this, "hlPrimesBoxClicked");
  hlNonPrimesBox = new GCheckbox(GUI, 10, 370, 171, 20);
  hlNonPrimesBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  hlNonPrimesBox.setText("highlight non-primes (blue)");
  hlNonPrimesBox.setOpaque(false);
  hlNonPrimesBox.addEventHandler(this, "hlNonPrimesBoxClicked");
  polynomialCField = new GTextField(GUI, 95, 280, 25, 17, G4P.SCROLLBARS_NONE);
  polynomialCField.setText("0");
  polynomialCField.setOpaque(true);
  polynomialCField.addEventHandler(this, "polynomialCFieldChange");
  demo1Button = new GButton(GUI, 190, 280, 80, 30);
  demo1Button.setText("Demo 1");
  demo1Button.setLocalColorScheme(GCScheme.RED_SCHEME);
  demo1Button.addEventHandler(this, "demo1ButtonClicked");
  demo2Button = new GButton(GUI, 190, 320, 80, 30);
  demo2Button.setText("Demo 2");
  demo2Button.setLocalColorScheme(GCScheme.RED_SCHEME);
  demo2Button.addEventHandler(this, "demo2ButtonClicked");
  demo3Button = new GButton(GUI, 190, 360, 80, 30);
  demo3Button.setText("Demo 3");
  demo3Button.setLocalColorScheme(GCScheme.RED_SCHEME);
  demo3Button.addEventHandler(this, "demo3ButtonClicked");
  screenshotButton = new GButton(GUI, 153, 33, 105, 30);
  screenshotButton.setText("Take screenshot");
  screenshotButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  screenshotButton.addEventHandler(this, "screenshotButtonClicked");
  infoWindow = GWindow.getWindow(this, "Information", 0, 0, 320, 550, JAVA2D);
  infoWindow.noLoop();
  infoWindow.setActionOnClose(G4P.KEEP_OPEN);
  infoWindow.addDrawHandler(this, "infoWindowDraw");
  infoTitle1 = new GLabel(infoWindow, 7, 65, 69, 20);
  infoTitle1.setText("General:");
  infoTitle1.setOpaque(false);
  explanation1 = new GLabel(infoWindow, 7, 85, 311, 38);
  explanation1.setText("Save prime data - saves all primes currently stored to txt file for next program run");
  explanation1.setOpaque(false);
  infoBlurb = new GLabel(infoWindow, 5, 7, 304, 29);
  infoBlurb.setText("Explanations and limits for certain GUI settings are provided below");
  infoBlurb.setOpaque(false);
  infoTitle2 = new GLabel(infoWindow, 8, 165, 62, 20);
  infoTitle2.setText("Spiral:");
  infoTitle2.setOpaque(false);
  explanation2 = new GLabel(infoWindow, 7, 185, 306, 62);
  explanation2.setText("# of boxes in spiral - displays boxes up to the inputted number, must input a positive integer within a certain range to fit the boxes on screen (358801 - square, 357604 - triangle, 89269 - hexagon)");
  explanation2.setOpaque(false);
  explanation3 = new GLabel(infoWindow, 6, 125, 273, 28);
  explanation3.setText("Take screenshot - saves current frame in program Screenshots folder");
  explanation3.setOpaque(false);
  explanation4 = new GLabel(infoWindow, 5, 245, 317, 29);
  explanation4.setText("show number labels - limited to 2025 boxes to preserve clarity of number labels");
  explanation4.setOpaque(false);
  infoTitle3 = new GLabel(infoWindow, 7, 280, 80, 20);
  infoTitle3.setText("Polynomial:");
  infoTitle3.setOpaque(false);
  explanation5 = new GLabel(infoWindow, 7, 305, 303, 33);
  explanation5.setText("polynomial to highlight - input any integer coefficients to create a polynomial of the form 4x^2+bx+c");
  explanation5.setOpaque(false);
  explanation6 = new GLabel(infoWindow, 7, 335, 298, 68);
  explanation6.setText("When integer values are inputted in the polynomial, their positive integers outputs can be highlighted in the prime spiral -> primes occur much more frequently than usual in some of these polynomials");
  explanation6.setOpaque(false);
  dragLabel = new GLabel(infoWindow, 5, 38, 263, 20);
  dragLabel.setText("(drag info window if it blocks settings window)");
  dragLabel.setOpaque(false);
  demoExplanation1 = new GLabel(infoWindow, 7, 406, 299, 50);
  demoExplanation1.setText("Demo 1 -  a diagonal of the square spiral is highlighted, where primes occur more than non-primes for small values");
  demoExplanation1.setOpaque(false);
  demoExplanation2 = new GLabel(infoWindow, 7, 464, 306, 31);
  demoExplanation2.setText("Demo 2 - other than 3, no primes are highlighted as this polynomial can be factored");
  demoExplanation2.setOpaque(false);
  demoExplanation3 = new GLabel(infoWindow, 7, 506, 308, 33);
  demoExplanation3.setText("Demo 3 - the hexagon spiral highlights number with its own spiral shape");
  demoExplanation3.setOpaque(false);
  GUI.loop();
  infoWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow GUI;
GLabel generalTitle; 
GButton primeDataButton; 
GCheckbox displayInfoBox; 
GLabel spiralTitle; 
GTextField numCountField; 
GDropList spiralShapeList; 
GLabel numCountLabel; 
GLabel spiralShapeLabel; 
GCheckbox showLabelsBox; 
GLabel showLabelsLabel; 
GLabel polynomialTitle; 
GTextField polynomialBField; 
GLabel polynomialALabel; 
GLabel polynomialBLabel; 
GLabel polynomialLabel; 
GCheckbox hlPrimesBox; 
GCheckbox hlNonPrimesBox; 
GTextField polynomialCField; 
GButton demo1Button; 
GButton demo2Button; 
GButton demo3Button; 
GButton screenshotButton; 
GWindow infoWindow;
GLabel infoTitle1; 
GLabel explanation1; 
GLabel infoBlurb; 
GLabel infoTitle2; 
GLabel explanation2; 
GLabel explanation3; 
GLabel explanation4; 
GLabel infoTitle3; 
GLabel explanation5; 
GLabel explanation6; 
GLabel dragLabel; 
GLabel demoExplanation1; 
GLabel demoExplanation2; 
GLabel demoExplanation3; 
